FROM brendanrius/jupyter-c-kernel:latest
# Inspect the Dockerfile at:
# https://github.com/brendan-rius/jupyter-c-kernel

USER root

# set up port to access jupyter via browser
EXPOSE 8888
USER jovyan

