name: pi1_docker

services:
  pi1_main:
    container_name: pi1-main
    build: ./pi1-main
    ports:
      - "8889:8888"
      - "4040-4049:4040-4049"
    volumes:
      - ./shared:/home/jovyan/shared
    environment:
      - PASSWORD=pi1
      - JUPYTER_TOKEN=pi1
      - JUPYTER_ALLOW_INSECURE_WRITES=true
      - JUPYTER_RUNTIME_DIR=/tmp/jupyter_runtime/
      - RJK_CLASSPATH=/usr/local/spark/jars/*

  mysql:
    image: mysql:8.0
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 20
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy

  mongo:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: root      
      MONGO_INITDB_DATABASE: db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root

volumes:
  mysql-data:
    driver: local
  mongo-data:
    driver: local
