name: pi1_docker

services:
  pi1_main:
    container_name: pi1-main
    build: ./pi1-main
    ports:
      - "8889:8888"
      - "4040-4049:4040-4049"
    volumes:
      - ./shared:/home/jovyan/shared
    environment:
      - PASSWORD=pi1
      - JUPYTER_TOKEN=pi1
      - JUPYTER_ALLOW_INSECURE_WRITES=true
      - JUPYTER_RUNTIME_DIR=/tmp/jupyter_runtime/
      - RJK_CLASSPATH=/usr/local/spark/jars/*

