name: pi1_docker

services:
  pi1_main:
    container_name: pi1-main
    build: ./pi1-main
    ports:
      - "8889:8888"
      - "4040-4049:4040-4049"
    volumes:
      - ./shared:/home/jovyan/shared
    environment:
      - PASSWORD=pi1
      - JUPYTER_TOKEN=pi1
      - JUPYTER_ALLOW_INSECURE_WRITES=true
      - JUPYTER_RUNTIME_DIR=/tmp/jupyter_runtime/
      - RJK_CLASSPATH=/usr/local/spark/jars/*

  mysql:
    image: mysql:8.0
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
